server:
  port: 8080

spring:
  application:
    name: triform
     
  datasource:
    url: jdbc:sqlite:${user.dir}/data/triform.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
